FROM httpd:2.4.52
COPY ./httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
COPY ./index1.html /usr/local/apache2/htdocs/html1/index.html
COPY ./index2.html /usr/local/apache2/htdocs/html2/index.html
COPY ./index3.html /usr/local/apache2/htdocs/html3/index.html
