FROM httpd:latest
COPY ./default.conf /usr/local/apache2/conf/default.conf
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./index1.html /usr/local/apache2/htdocs/html1/index.html
COPY ./index2.html /usr/local/apache2/htdocs/html2/index.html
COPY ./index3.html /usr/local/apache2/htdocs/html3/index.html